name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # You can specify other distributions if needed

    - name: Build with Maven
      run: |
        cd MakeSoft  # Change to the MakeSoft directory
        mvn clean install  # Clean and install the project dependencies

    - name: Run tests
      run: |
        cd MakeSoft  # Change to the MakeSoft directory again
        mvn test  # Execute the tests defined in the project
