name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: PeerReview
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'  # You can specify other distributions if needed

    - name: Build with Maven
      run: |
        cd MakeSoft  # Change to the MakeSoft directory
        mvn clean install  # Clean and install the project dependencies

    - name: Run tests
      run: |
        cd MakeSoft  # Change to the MakeSoft directory again
        mvn test -X  # Execute the tests with full debug logging
