name: CI Pipeline with SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_sonar:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: PeerReview
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # 1. Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'  # You can change to 'zulu' if preferred

      # 3. Cache Maven dependencies to speed up builds
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            !~/.m2/repository/org/apache/maven/plugins/maven-surefire-plugin/**/surefire-*.jar
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Build the project to generate .class files
      - name: Build Project
        run: |
          cd MakeSoft  # Navigate to the MakeSoft directory
          mvn clean install --batch-mode --show-version

      # 5. Run tests with full debug logging
      - name: Run Tests
        run: |
          cd MakeSoft  # Navigate to the MakeSoft directory again
          mvn test -X  # Execute the tests with full debug logging
          
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: sqp_1f282815b5e8246b3b4e000bc91136d305f317b5
        run: |
          cd MakeSoft  # Navigate to the MakeSoft directory
          mvn sonar:sonar \
            -Dsonar.projectKey=project \
            -Dsonar.host.url=https://38aa-69-158-46-54.ngrok-free.app \
            -Dsonar.login=sqp_1f282815b5e8246b3b4e000bc91136d305f317b5 
            
