name: sign in test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: PeerReview
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  

      - name: Build with Maven
        run: |
          cd MakeSoft  
          mvn clean install  

      - name: Run Java tests
        run: |
          cd MakeSoft  
          mvn test -X  

      # Node.js Setup for Jest Tests
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JavaScript dependencies
        run: |
          cd MakeSoft  
          npm install  

      - name: Run Jest tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/PeerReview
        run: |
          cd MakeSoft  
          npx jest signin.test.js
