name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
         java-version: '17'
         distribution: 'zulu'
    - name: Cache SonarQube scanner
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/pom.xml') }}

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        entryPoint: "/opt/sonar-scanner/bin/sonar-scanner"  # Use sonar-scanner
        args: |
          -Dsonar.projectKey=project
          -Dsonar.projectName=project
          -Dsonar.projectVersion=1.0
          -Dsonar.sources=src
          -Dsonar.java.binaries=target/classes
        token: ${{ secrets.SONAR_TOKEN }}
        projectBaseDir: ./ 
