name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run SonarQube Scanner
        run: |
          sonar-scanner \
            -Dsonar.projectKey=project \
            -Dsonar.sources=src \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_1f282815b5e8246b3b4e000bc91136d305f317b5
